/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pfiches;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JProgressBar;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import static pfiches.FAccueil.nomEntreprise;
import ptraitement.Main;

/**
 *
 * @author Bryan
 */
public class FMENUPART extends javax.swing.JFrame {
    

    /**
     * Creates new form FAccueil
     */
    public FMENUPART() {
        initComponents();
        this.setSize(1980, 1080); // taille manuelle (adapter selon ton design)
        jLabel1.setText("Bonjour "+nomEntreprise);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Background = new javax.swing.JPanel();
        jfirst_font = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel_LOGO = new javax.swing.JLabel();
        jButton_retour = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Demande = new javax.swing.JButton();
        historique_entr = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Background.setBackground(new java.awt.Color(0, 0, 0));
        jPanel_Background.setPreferredSize(new java.awt.Dimension(1280, 1024));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("MENU PARTICULIER");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfirst_fontLayout = new javax.swing.GroupLayout(jfirst_font);
        jfirst_font.setLayout(jfirst_fontLayout);
        jfirst_fontLayout.setHorizontalGroup(
            jfirst_fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfirst_fontLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addContainerGap())
        );
        jfirst_fontLayout.setVerticalGroup(
            jfirst_fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfirst_fontLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel_LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfiches/EPF_LOGO (2).png"))); // NOI18N

        jButton_retour.setBackground(new java.awt.Color(255, 0, 51));
        jButton_retour.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jButton_retour.setForeground(new java.awt.Color(255, 255, 255));
        jButton_retour.setText("Déconnexion");
        jButton_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_retourActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        Demande.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        Demande.setText("Rechercher un centre");
        Demande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemandeActionPerformed(evt);
            }
        });

        historique_entr.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        historique_entr.setText("Historique de dépôts");
        historique_entr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historique_entrActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jButton1.setText("Supprimer le compte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jButton2.setText("Modifier les données");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Demande, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historique_entr, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Demande, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historique_entr, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout jPanel_BackgroundLayout = new javax.swing.GroupLayout(jPanel_Background);
        jPanel_Background.setLayout(jPanel_BackgroundLayout);
        jPanel_BackgroundLayout.setHorizontalGroup(
            jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addGroup(jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BackgroundLayout.createSequentialGroup()
                        .addComponent(jfirst_font, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(395, 395, 395))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BackgroundLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(277, 277, 277)))
                .addComponent(jLabel_LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(389, 389, 389))
            .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_BackgroundLayout.setVerticalGroup(
            jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                        .addComponent(jLabel_LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(491, 491, 491)
                        .addComponent(jButton_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                        .addComponent(jfirst_font, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(335, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Background, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_retourActionPerformed
    Main.Session.mailEntreprise = "0";
    // Affiche une popup d'information
    JOptionPane.showMessageDialog(this, "Vous avez bien été déconnecté.");
    // Ferme la fenêtre actuelle et ouvre le menu principal
    this.dispose();
    FAccueil menu = new FAccueil();
    menu.setLocationRelativeTo(null); // Centre la fenêtre à l'écran
    menu.setVisible(true);
    }//GEN-LAST:event_jButton_retourActionPerformed

    private void DemandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemandeActionPerformed
        FCHERCHE menu = new FCHERCHE();
        menu.setLocationRelativeTo(null); // Centre la fenêtre à l'écran
        menu.setVisible(true);

    }//GEN-LAST:event_DemandeActionPerformed

    private void historique_entrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historique_entrActionPerformed
        FHISTORIQUE_PART menu = new FHISTORIQUE_PART();
        menu.setLocationRelativeTo(null); // Centre la fenêtre à l'écran
        menu.setVisible(true);
    }//GEN-LAST:event_historique_entrActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Création de la fenêtre de confirmation de suppression
JDialog confirmationDialog = new JDialog(this, "Confirmer la suppression", true);
confirmationDialog.setSize(400, 250);
confirmationDialog.setLocationRelativeTo(this);

// Panel principal
JPanel panel = new JPanel();
panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

// Composants de la fenêtre
JLabel emailLabel = new JLabel("Entrez votre email:");
JTextField emailField = new JTextField(20);
JLabel passwordLabel = new JLabel("Entrez votre mot de passe:");
JPasswordField passwordField = new JPasswordField(20);

JCheckBox confirmCheckBox = new JCheckBox("Je confirme la suppression de mon compte.");

// Boutons pour confirmer ou annuler
JButton confirmButton = new JButton("Confirmer");
JButton cancelButton = new JButton("Annuler");

// Ajouter les éléments au panel
panel.add(emailLabel);
panel.add(emailField);
panel.add(passwordLabel);
panel.add(passwordField);
panel.add(confirmCheckBox);
panel.add(confirmButton);
panel.add(cancelButton);

// Ajouter le panel à la fenêtre de confirmation
confirmationDialog.add(panel);

// Action pour confirmer la suppression
confirmButton.addActionListener(e -> {
    String email = emailField.getText().trim();
    String password = new String(passwordField.getPassword()).trim();

    boolean accountExists = false;
    boolean passwordCorrect = false;

    // Vérification des identifiants dans Utilisateur.txt
    try (BufferedReader reader = new BufferedReader(new FileReader("utilisateurs.txt"))) {
        String line;
        while ((line = reader.readLine()) != null) {
            String[] data = line.split(";");
            if (data.length >= 3) {
                String storedEmail = data[2].trim();
                String storedPassword = data[3].trim();
                if (storedEmail.equals(email)) {
                    accountExists = true;
                    if (storedPassword.equals(password)) {
                        passwordCorrect = true;
                    }
                    break;
                }
            }
        }
    } catch (IOException ex) {
        ex.printStackTrace();
    }

    // Si l'email et le mot de passe sont corrects
    if (accountExists && passwordCorrect) {
        if (confirmCheckBox.isSelected()) {
            // Affichage de la barre de progression de suppression
            JProgressBar progressBar = new JProgressBar(0, 100);
            progressBar.setStringPainted(true);
            progressBar.setValue(0);
            JFrame progressFrame = new JFrame("Suppression en cours...");
            progressFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            progressFrame.setSize(300, 100);
            progressFrame.setLocationRelativeTo(this);
            progressFrame.add(progressBar);
            progressFrame.setVisible(true);

            // Thread pour gérer la suppression en arrière-plan
            new Thread(() -> {
                try {
                    String line;

                    // Suppression dans utilisateurs.txt
                    File utilisateursFile = new File("utilisateurs.txt");
                    BufferedReader fileReader = new BufferedReader(new FileReader(utilisateursFile));
                    StringBuilder content = new StringBuilder();

                    while ((line = fileReader.readLine()) != null) {
                        if (!line.contains(email)) {
                            content.append(line).append("\n");
                        }
                    }
                    fileReader.close();

                    BufferedWriter fileWriter = new BufferedWriter(new FileWriter(utilisateursFile));
                    fileWriter.write(content.toString());
                    fileWriter.close();

                    // Suppression des demandes dans demandes.txt
                    File demandesFile = new File("demandes.txt");
                    BufferedReader demandesReader = new BufferedReader(new FileReader(demandesFile));
                    StringBuilder demandesContent = new StringBuilder();

                    while ((line = demandesReader.readLine()) != null) {
                        if (!line.contains(email)) {
                            demandesContent.append(line).append("\n");
                        }
                    }
                    demandesReader.close();

                    BufferedWriter demandesWriter = new BufferedWriter(new FileWriter(demandesFile));
                    demandesWriter.write(demandesContent.toString());
                    demandesWriter.close();

                    // Suppression des dépôts dans depots.txt
                    File depotsFile = new File("depots.txt");
                    BufferedReader depotsReader = new BufferedReader(new FileReader(depotsFile));
                    StringBuilder depotsContent = new StringBuilder();

                    while ((line = depotsReader.readLine()) != null) {
                        String[] parts = line.split(";");
                        if (parts.length >= 1 && !parts[0].equals(email)) {
                            depotsContent.append(line).append("\n");
                        }
                    }
                    depotsReader.close();

                    BufferedWriter depotsWriter = new BufferedWriter(new FileWriter(depotsFile));
                    depotsWriter.write(depotsContent.toString());
                    depotsWriter.close();

                    // Simuler une barre de progression
                    for (int i = 0; i <= 100; i++) {
                        final int value = i;
                        SwingUtilities.invokeLater(() -> progressBar.setValue(value));
                        Thread.sleep(50);
                    }

                    // Confirmation de la suppression
                    SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(this, "Votre compte a été supprimé avec succès.");
                        FAccueil.mailEntreprise = null;
                        progressFrame.dispose();
                        confirmationDialog.dispose();
                        this.dispose();
                        new FAccueil().setVisible(true);
                    });

                } catch (IOException | InterruptedException ex) {
                    ex.printStackTrace();
                    SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(this, "Erreur lors de la suppression du compte.");
                        progressFrame.dispose();
                    });
                }
            }).start();

        } else {
            JOptionPane.showMessageDialog(confirmationDialog, "Veuillez confirmer la suppression du compte.");
        }

    } else if (!accountExists) {
        JOptionPane.showMessageDialog(confirmationDialog, "Aucun compte trouvé avec cet email.");
    } else {
        JOptionPane.showMessageDialog(confirmationDialog, "Mot de passe incorrect.");
    }
});

// Action pour annuler la suppression
cancelButton.addActionListener(e -> confirmationDialog.dispose());

// Affichage de la fenêtre de confirmation
confirmationDialog.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
JDialog dialog = new JDialog(this, "Modifier mes données", true);
dialog.setSize(500, 500);
dialog.setLocationRelativeTo(this);
dialog.setLayout(new GridBagLayout());
GridBagConstraints gbc = new GridBagConstraints();
gbc.insets = new Insets(5, 5, 5, 5);
gbc.anchor = GridBagConstraints.WEST;

String emailActuel = (String) FAccueil.mailEntreprise;
String[] ligneUtilisateur = null;

try (BufferedReader reader = new BufferedReader(new FileReader("utilisateurs.txt"))) {
    String line;
    while ((line = reader.readLine()) != null) {
        if (line.contains(emailActuel)) {
            ligneUtilisateur = line.split(";");
            break;
        }
    }
} catch (IOException ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Erreur lors du chargement des données.");
    return;
}

if (ligneUtilisateur == null || ligneUtilisateur.length < 7) {
    JOptionPane.showMessageDialog(this, "Utilisateur introuvable ou données incomplètes.");
    return;
}

String ancienEmail = emailActuel;

// Champs
JLabel typeLabel = new JLabel("Type de compte:");
JTextField typeField = new JTextField(ligneUtilisateur[0], 20);
typeField.setEditable(false);
typeField.setBackground(Color.LIGHT_GRAY);

JLabel nomLabel = new JLabel("Nom:");
JTextField nomField = new JTextField(ligneUtilisateur[1], 20);

JLabel prenomLabel = new JLabel("Prénom:");
JTextField prenomField = new JTextField(ligneUtilisateur[6], 20);

JLabel emailLabel = new JLabel("Email:");
JTextField emailField = new JTextField(ligneUtilisateur[2], 20);

JLabel mdpLabel = new JLabel("Mot de passe:");
JPasswordField mdpField = new JPasswordField(ligneUtilisateur[3], 20);
JCheckBox showPwd = new JCheckBox("Afficher");

JLabel adresseLabel = new JLabel("Adresse:");
JTextField adresseField = new JTextField(ligneUtilisateur[4], 20);

JLabel telLabel = new JLabel("Téléphone:");
JTextField telField = new JTextField(ligneUtilisateur[5], 20);

JLabel info = new JLabel("<html><i>Si vous souhaitez changer de type de compte, contactez un administrateur :<br>bryan.thirimanna@epfedu.fr ou gabriel.bremme@epfedu.fr</i></html>");

// Affichage des composants
int y = 0;
gbc.gridx = 0; gbc.gridy = y; dialog.add(typeLabel, gbc);
gbc.gridx = 1; dialog.add(typeField, gbc); y++;

gbc.gridx = 0; gbc.gridy = y; dialog.add(prenomLabel, gbc);
gbc.gridx = 1; dialog.add(prenomField, gbc); y++;

gbc.gridx = 0; gbc.gridy = y; dialog.add(nomLabel, gbc);
gbc.gridx = 1; dialog.add(nomField, gbc); y++;

gbc.gridx = 0; gbc.gridy = y; dialog.add(emailLabel, gbc);
gbc.gridx = 1; dialog.add(emailField, gbc); y++;

gbc.gridx = 0; gbc.gridy = y; dialog.add(mdpLabel, gbc);
gbc.gridx = 1; dialog.add(mdpField, gbc);
gbc.gridx = 2; dialog.add(showPwd, gbc); y++;

gbc.gridx = 0; gbc.gridy = y; dialog.add(adresseLabel, gbc);
gbc.gridx = 1; dialog.add(adresseField, gbc); y++;

gbc.gridx = 0; gbc.gridy = y; dialog.add(telLabel, gbc);
gbc.gridx = 1; dialog.add(telField, gbc); y++;

gbc.gridx = 0; gbc.gridy = y; gbc.gridwidth = 3; dialog.add(info, gbc); y++;

// Affichage mot de passe
showPwd.addActionListener(e -> {
    mdpField.setEchoChar(showPwd.isSelected() ? (char) 0 : '\u2022');
});

// Boutons
JButton enregistrerBtn = new JButton("Enregistrer");
gbc.gridx = 1; gbc.gridy = y;
dialog.add(enregistrerBtn, gbc);
JButton retourBtn = new JButton("Retour");
gbc.gridx = 2;
dialog.add(retourBtn, gbc);

retourBtn.addActionListener(ev -> dialog.dispose());

enregistrerBtn.addActionListener(e -> {
    String nouveauType = typeField.getText();
    String nouveauNom = nomField.getText();
    String nouveauEmail = emailField.getText().trim();
    String nouveauMdp = new String(mdpField.getPassword());
    String nouvelleAdresse = adresseField.getText();
    String nouveauTel = telField.getText();
    String nouveauPrenom = prenomField.getText();

    // Vérifier unicité du nouvel email
    try (BufferedReader reader = new BufferedReader(new FileReader("utilisateurs.txt"))) {
        String line;
        while ((line = reader.readLine()) != null) {
            if (!line.contains(emailActuel) && line.split(";")[2].equalsIgnoreCase(nouveauEmail)) {
                JOptionPane.showMessageDialog(dialog, "Cet email est déjà utilisé par un autre compte.");
                return;
            }
        }
    } catch (IOException ex) {
        ex.printStackTrace();
    }

    // Mise à jour du fichier utilisateurs
    try {
        File file = new File("utilisateurs.txt");
        BufferedReader reader = new BufferedReader(new FileReader(file));
        StringBuilder contenu = new StringBuilder();
        String line;

        while ((line = reader.readLine()) != null) {
            if (line.contains(emailActuel)) {
                String nouvelleLigne = String.join(";", nouveauType, nouveauNom, nouveauEmail, nouveauMdp, nouvelleAdresse, nouveauTel, nouveauPrenom);
                contenu.append(nouvelleLigne).append("\n");
            } else {
                contenu.append(line).append("\n");
            }
        }
        reader.close();

        BufferedWriter writer = new BufferedWriter(new FileWriter(file));
        writer.write(contenu.toString());
        writer.close();

        // Si c’est un particulier, mettre à jour les mails dans depots.txt
        if (nouveauType.equals("PARTICULIER") && !ancienEmail.equals(nouveauEmail)) {
            File depotsFile = new File("depots.txt");
            BufferedReader depotsReader = new BufferedReader(new FileReader(depotsFile));
            StringBuilder depotsContent = new StringBuilder();

            while ((line = depotsReader.readLine()) != null) {
                String[] parts = line.split(";");
                if (parts.length >= 5 && parts[0].equals(ancienEmail)) {
                    parts[0] = nouveauEmail; // Mettre à jour l'email du particulier
                    depotsContent.append(String.join(";", parts)).append("\n");
                } else {
                    depotsContent.append(line).append("\n");
                }
            }
            depotsReader.close();

            BufferedWriter depotsWriter = new BufferedWriter(new FileWriter(depotsFile));
            depotsWriter.write(depotsContent.toString());
            depotsWriter.close();
        }

        FAccueil.mailEntreprise = nouveauEmail;
        JOptionPane.showMessageDialog(dialog, "Données modifiées avec succès.");
        dialog.dispose();
    } catch (IOException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(dialog, "Erreur lors de la sauvegarde.");
    }
});
    jLabel1.setText("Bienvenue "+nomEntreprise);
dialog.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMENUPART.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMENUPART.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMENUPART.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMENUPART.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FMENUPART().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Demande;
    private javax.swing.JButton historique_entr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_retour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_LOGO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Background;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jfirst_font;
    // End of variables declaration//GEN-END:variables
}
