
package pfiches;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JProgressBar;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import static pfiches.FAccueil.mailEntreprise;
import ptraitement.Main;

/**
 *
 * @author Bryan
 */
public class FMenuCENTRE extends javax.swing.JFrame {


    /**
     * Creates new form FAccueil
     */
    public FMenuCENTRE() {
    initComponents();

    String nom = "Inconnu"; // Valeur par défaut
    try {
        try (BufferedReader br = new BufferedReader(new FileReader("Utilisateurs.txt"))) {
            String ligne;
            while ((ligne = br.readLine()) != null) {
                String[] donnees = ligne.split(";");
                if (donnees.length >= 3 && donnees[2].equalsIgnoreCase((String) mailEntreprise)) {
                    nom = donnees[1]; // Le nom est à l'index 1
                    break;
                }
            }
            jTextField2.setText("Bienvenue "+nom);
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
        this.setSize(1980, 1080); // taille manuelle (adapter selon ton design)

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Background = new javax.swing.JPanel();
        jfirst_font = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel_LOGO = new javax.swing.JLabel();
        jButton_retour = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Demande = new javax.swing.JButton();
        historique_entr = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Background.setBackground(new java.awt.Color(0, 0, 0));
        jPanel_Background.setPreferredSize(new java.awt.Dimension(1280, 1024));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("MENU CENTRE DE RECYCLAGE");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfirst_fontLayout = new javax.swing.GroupLayout(jfirst_font);
        jfirst_font.setLayout(jfirst_fontLayout);
        jfirst_fontLayout.setHorizontalGroup(
            jfirst_fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfirst_fontLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addContainerGap())
        );
        jfirst_fontLayout.setVerticalGroup(
            jfirst_fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfirst_fontLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel_LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfiches/EPF_LOGO (2).png"))); // NOI18N

        jButton_retour.setBackground(new java.awt.Color(255, 0, 51));
        jButton_retour.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jButton_retour.setForeground(new java.awt.Color(255, 255, 255));
        jButton_retour.setText("Déconnexion");
        jButton_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_retourActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        Demande.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        Demande.setText("Gestion des demandes");
        Demande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemandeActionPerformed(evt);
            }
        });

        historique_entr.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        historique_entr.setText("Gestion des dépôts");
        historique_entr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historique_entrActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jButton1.setText("Supprimer le compte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jButton2.setText("Modifier les données");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Demande, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historique_entr, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Demande, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historique_entr, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout jPanel_BackgroundLayout = new javax.swing.GroupLayout(jPanel_Background);
        jPanel_Background.setLayout(jPanel_BackgroundLayout);
        jPanel_BackgroundLayout.setHorizontalGroup(
            jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                .addContainerGap(480, Short.MAX_VALUE)
                .addComponent(jfirst_font, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(395, 395, 395)
                .addComponent(jLabel_LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(389, 389, 389))
            .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                .addGroup(jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_BackgroundLayout.setVerticalGroup(
            jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                        .addComponent(jLabel_LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(491, 491, 491)
                        .addComponent(jButton_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                        .addComponent(jfirst_font, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(335, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Background, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_retourActionPerformed
    Main.Session.mailEntreprise = "0";
    // Affiche une popup d'information
    JOptionPane.showMessageDialog(this, "Vous avez bien été déconnecté.");
    // Ferme la fenêtre actuelle et ouvre le menu principal
    this.dispose();
    FAccueil menu = new FAccueil();
    menu.setLocationRelativeTo(null); // Centre la fenêtre à l'écran
    menu.setVisible(true);
    }//GEN-LAST:event_jButton_retourActionPerformed

    private void DemandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemandeActionPerformed
        FCOLLECTE menu = new FCOLLECTE();
        menu.setLocationRelativeTo(null); // Centre la fenêtre à l'écran
        menu.setVisible(true);
    }//GEN-LAST:event_DemandeActionPerformed

    private void historique_entrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historique_entrActionPerformed
        FDEPOTSCEN menu = new FDEPOTSCEN();
        menu.setLocationRelativeTo(null); // Centre la fenêtre à l'écran
        menu.setVisible(true);
    }//GEN-LAST:event_historique_entrActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Création de la fenêtre de confirmation de suppression
JDialog confirmationDialog = new JDialog(this, "Confirmer la suppression", true);
confirmationDialog.setSize(400, 250);
confirmationDialog.setLocationRelativeTo(this);

// Panel principal
JPanel panel = new JPanel();
panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

// Composants de la fenêtre
JLabel emailLabel = new JLabel("Entrez votre email:");
JTextField emailField = new JTextField(20);
JLabel passwordLabel = new JLabel("Entrez votre mot de passe:");
JPasswordField passwordField = new JPasswordField(20);

JCheckBox confirmCheckBox = new JCheckBox("Je confirme la suppression de mon compte.");

// Boutons pour confirmer ou annuler
JButton confirmButton = new JButton("Confirmer");
JButton cancelButton = new JButton("Annuler");

// Ajouter les éléments au panel
panel.add(emailLabel);
panel.add(emailField);
panel.add(passwordLabel);
panel.add(passwordField);
panel.add(confirmCheckBox);
panel.add(confirmButton);
panel.add(cancelButton);

// Ajouter le panel à la fenêtre de confirmation
confirmationDialog.add(panel);

// Action pour confirmer la suppression
confirmButton.addActionListener(e -> {
    String email = emailField.getText().trim();
    String password = new String(passwordField.getPassword()).trim();

    boolean accountExists = false;
    boolean passwordCorrect = false;

    // Vérification des identifiants dans Utilisateur.txt
    try (BufferedReader reader = new BufferedReader(new FileReader("utilisateurs.txt"))) {
        String line;
        while ((line = reader.readLine()) != null) {
            String[] data = line.split(";");
            if (data.length >= 3) {
                String storedEmail = data[2].trim(); // Utiliser la variable mailEntreprise
                String storedPassword = data[3].trim();
                if (storedEmail.equals(email)) {
                    accountExists = true;
                    if (storedPassword.equals(password)) {
                        passwordCorrect = true;
                    }
                    break;  // Compte trouvé, pas besoin de continuer
                }
            }
        }
    } catch (IOException ex) {
        ex.printStackTrace();
    }

    // Si l'email et le mot de passe sont corrects
    if (accountExists && passwordCorrect) {
        if (confirmCheckBox.isSelected()) {
            // Affichage de la barre de progression de suppression
            JProgressBar progressBar = new JProgressBar(0, 100);
            progressBar.setStringPainted(true);
            progressBar.setValue(0);
            JFrame progressFrame = new JFrame("Suppression en cours...");
            progressFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            progressFrame.setSize(300, 100);
            progressFrame.setLocationRelativeTo(this);
            progressFrame.add(progressBar);
            progressFrame.setVisible(true);

            // Thread pour gérer la suppression en arrière-plan
            new Thread(() -> {
                try {
                    // Suppression dans Utilisateur.txt
                    File utilisateursFile = new File("utilisateurs.txt");
                    BufferedReader fileReader = new BufferedReader(new FileReader(utilisateursFile));
                    StringBuilder content = new StringBuilder();
                    String line;

                    while ((line = fileReader.readLine()) != null) {
                        if (!line.contains(email)) {
                            content.append(line).append("\n");
                        }
                    }
                    fileReader.close();

                    BufferedWriter fileWriter = new BufferedWriter(new FileWriter(utilisateursFile));
                    fileWriter.write(content.toString());
                    fileWriter.close();

                    // Suppression des demandes dans Demandes.txt
                    File demandesFile = new File("demandes.txt");
                    BufferedReader demandesReader = new BufferedReader(new FileReader(demandesFile));
                    StringBuilder demandesContent = new StringBuilder();

                    while ((line = demandesReader.readLine()) != null) {
                        if (!line.contains(email)) {
                            demandesContent.append(line).append("\n");
                        }
                    }
                    demandesReader.close();

                    BufferedWriter demandesWriter = new BufferedWriter(new FileWriter(demandesFile));
                    demandesWriter.write(demandesContent.toString());
                    demandesWriter.close();

                    // Suppression des dépôts dans Depots.txt
                    File depotsFile = new File("depots.txt");
                    BufferedReader depotsReader = new BufferedReader(new FileReader(depotsFile));
                    StringBuilder depotsContent = new StringBuilder();

                    while ((line = depotsReader.readLine()) != null) {
                        if (!line.contains(email)) {
                            depotsContent.append(line).append("\n");
                        }
                    }
                    depotsReader.close();

                    BufferedWriter depotsWriter = new BufferedWriter(new FileWriter(depotsFile));
                    depotsWriter.write(depotsContent.toString());
                    depotsWriter.close();

                    // Simuler une barre de progression
                    for (int i = 0; i <= 100; i++) {
                        final int value = i;
                        SwingUtilities.invokeLater(() -> progressBar.setValue(value));
                        Thread.sleep(50);  // Simuler un temps de suppression
                    }

                    // Confirmation de la suppression
                    SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(this, "Votre compte a été supprimé avec succès.");
                        FAccueil.mailEntreprise = null;  // Réinitialisation de l'email
                        progressFrame.dispose();  // Fermer la fenêtre de progression
                        confirmationDialog.dispose();  // Fermer le dialogue de confirmation
                        this.dispose();  // Fermer la fenêtre actuelle
                        new FAccueil().setVisible(true);  // Retour au menu principal
                    });
                } catch (IOException | InterruptedException ex) {
                    ex.printStackTrace();
                    SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(this, "Erreur lors de la suppression du compte.");
                        progressFrame.dispose();
                    });
                }
            }).start();
        } else {
            JOptionPane.showMessageDialog(confirmationDialog, "Veuillez confirmer la suppression du compte.");
        }
    } else if (!accountExists) {
        JOptionPane.showMessageDialog(confirmationDialog, "Aucun compte trouvé avec cet email.");
    } else {
        JOptionPane.showMessageDialog(confirmationDialog, "Mot de passe incorrect.");
    }
});

// Action pour annuler la suppression
cancelButton.addActionListener(e -> confirmationDialog.dispose());

// Affichage de la fenêtre de confirmation
confirmationDialog.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // Code complet mis à jour pour modification des données d'un centre de recyclage
    JDialog dialog = new JDialog(this, "Modifier mes données", true);
    dialog.setSize(600, 650);
    dialog.setLocationRelativeTo(this);
    dialog.setLayout(new GridBagLayout());
    GridBagConstraints gbc = new GridBagConstraints();
    gbc.insets = new Insets(5, 5, 5, 5);
    gbc.anchor = GridBagConstraints.WEST;

    String emailActuel = (String) FAccueil.mailEntreprise;
    String[] ligneUtilisateur = null;

    try (BufferedReader reader = new BufferedReader(new FileReader("utilisateurs.txt"))) {
        String line;
        while ((line = reader.readLine()) != null) {
            if (line.contains(emailActuel)) {
                ligneUtilisateur = line.split(";");
                break;
            }
        }
    } catch (IOException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur lors du chargement des données.");
        return;
    }

    if (ligneUtilisateur == null || ligneUtilisateur.length < 6) {
        JOptionPane.showMessageDialog(this, "Utilisateur introuvable ou données incomplètes.");
        return;
    }

    // Champs de base
    JLabel typeLabel = new JLabel("Type de compte:");
    JTextField typeField = new JTextField("Centre", 20);
    typeField.setEditable(false);
    typeField.setForeground(Color.GRAY);
    typeField.setBackground(Color.LIGHT_GRAY);

    JLabel nomLabel = new JLabel("Nom:");
    JTextField nomField = new JTextField(ligneUtilisateur[1], 20);

    JLabel emailLabel = new JLabel("Email:");
    JTextField emailField = new JTextField(ligneUtilisateur[2], 20);

    JLabel mdpLabel = new JLabel("Mot de passe:");
    JPasswordField mdpField = new JPasswordField(ligneUtilisateur[3], 20);
    JCheckBox showPwd = new JCheckBox("Afficher");

    JLabel telLabel = new JLabel("Téléphone:");
    JTextField telField = new JTextField(ligneUtilisateur[5], 20);

    JLabel adresseLabel = new JLabel("Adresse:");
    JTextField adresseField = new JTextField(ligneUtilisateur[4], 20);

    JLabel heureOuvLabel = new JLabel("Heure d'ouverture (HH:MM):");
    JTextField heureOuvField = new JTextField(ligneUtilisateur[6], 20);

    JLabel heureFermLabel = new JLabel("Heure de fermeture (HH:MM):");
    JTextField heureFermField = new JTextField(ligneUtilisateur[7], 20);

    JLabel capaciteLabel = new JLabel("Capacité de stockage:");
    JTextField capaciteField = new JTextField(ligneUtilisateur[8], 20);

    String[] types = {"Plastique", "Papier", "Verre", "Métaux", "Organique", "Carton", "Batteries", "Textile", "Electronique"};
    ArrayList<JCheckBox> checkBoxes = new ArrayList<>();

    for (String t : types) {
        JCheckBox cb = new JCheckBox(t);
        for (int i = 9; i < ligneUtilisateur.length; i++) {
            if (ligneUtilisateur[i].equalsIgnoreCase(t)) {
                cb.setSelected(true);
                break;
            }
        }
        checkBoxes.add(cb);
    }

    // Créer un JPanel avec un GridLayout de 3 lignes et 3 colonnes pour les cases à cocher
    JPanel gridPanel = new JPanel();
    gridPanel.setLayout(new GridLayout(3, 3));  // 3 lignes et 3 colonnes

    // Ajouter les cases à cocher au panel
    for (JCheckBox cb : checkBoxes) {
        gridPanel.add(cb);
    }

    // Créer le JDialog
    JLabel info = new JLabel("<html><i>Si vous souhaitez changer de type de compte, contactez un administrateur :<br>bryan.thirimanna@epfedu.fr ou gabriel.bremme@epfedu.fr</i></html>");

    // Ajout dans le panel avec GridBagLayout
    int y = 0;
    gbc.gridx = 0; gbc.gridy = y; dialog.add(typeLabel, gbc);
    gbc.gridx = 1; dialog.add(typeField, gbc); y++;

    gbc.gridx = 0; gbc.gridy = y; dialog.add(nomLabel, gbc);
    gbc.gridx = 1; dialog.add(nomField, gbc); y++;

    gbc.gridx = 0; gbc.gridy = y; dialog.add(emailLabel, gbc);
    gbc.gridx = 1; dialog.add(emailField, gbc); y++;

    gbc.gridx = 0; gbc.gridy = y; dialog.add(mdpLabel, gbc);
    gbc.gridx = 1; dialog.add(mdpField, gbc);
    gbc.gridx = 2; dialog.add(showPwd, gbc); y++;

    gbc.gridx = 0; gbc.gridy = y; dialog.add(telLabel, gbc);
    gbc.gridx = 1; dialog.add(telField, gbc); y++;

    gbc.gridx = 0; gbc.gridy = y; dialog.add(adresseLabel, gbc);
    gbc.gridx = 1; dialog.add(adresseField, gbc); y++;

    gbc.gridx = 0; gbc.gridy = y; dialog.add(heureOuvLabel, gbc);
    gbc.gridx = 1; dialog.add(heureOuvField, gbc); y++;

    gbc.gridx = 0; gbc.gridy = y; dialog.add(heureFermLabel, gbc);
    gbc.gridx = 1; dialog.add(heureFermField, gbc); y++;

    gbc.gridx = 0; gbc.gridy = y; dialog.add(capaciteLabel, gbc);
    gbc.gridx = 1; dialog.add(capaciteField, gbc); y++;

    // Ajouter le panneau contenant les cases à cocher
    gbc.gridx = 0; gbc.gridy = y; gbc.gridwidth = 3;
    dialog.add(gridPanel, gbc); y++;

    // Ajouter l'information en bas
    gbc.gridx = 0; gbc.gridy = y; gbc.gridwidth = 3;
    dialog.add(info, gbc); y++;

    // Gestion de l'affichage du mot de passe
    showPwd.addActionListener(e -> {
        mdpField.setEchoChar(showPwd.isSelected() ? (char) 0 : '\u2022');
    });

    // Boutons
    JButton enregistrerBtn = new JButton("Enregistrer");
    gbc.gridx = 1; gbc.gridy = y;
    dialog.add(enregistrerBtn, gbc);
    JButton retourBtn = new JButton("Retour");
    gbc.gridx = 2;
    dialog.add(retourBtn, gbc);

    retourBtn.addActionListener(ev -> dialog.dispose());

    enregistrerBtn.addActionListener((ActionEvent e) -> {
        String nouveauNom = nomField.getText();
        String nouveauEmail = emailField.getText();
        String nouveauMdp = new String(mdpField.getPassword());
        String nouvelleAdresse = adresseField.getText();
        String nouveauTel = telField.getText();
        String nouvelleHeureOuv = heureOuvField.getText();
        String nouvelleHeureFerm = heureFermField.getText();
        String nouvelleCapacite = capaciteField.getText();

        boolean emailExistant = false;
        try (BufferedReader reader = new BufferedReader(new FileReader("utilisateurs.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] elements = line.split(";");
                if (elements.length > 2 && elements[2].equalsIgnoreCase(nouveauEmail) && !elements[2].equalsIgnoreCase(emailActuel)) {
                    emailExistant = true;
                    break;
                }
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }

        // Si l'email existe déjà, afficher un message d'erreur
        if (emailExistant) {
            JOptionPane.showMessageDialog(dialog, "Cet email est déjà utilisé par un autre compte.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean caseCochee = false;
        for (JCheckBox cb : checkBoxes) {
            if (cb.isSelected()) {
                caseCochee = true;
                break;
            }
        }

        // Si aucune case n'est cochée, afficher un message d'erreur
        if (!caseCochee) {
            JOptionPane.showMessageDialog(dialog, "Vous devez sélectionner au moins un type de déchet.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!nouvelleHeureOuv.matches("\\d{2}:\\d{2}") || !nouvelleHeureFerm.matches("\\d{2}:\\d{2}")) {
            JOptionPane.showMessageDialog(dialog, "Format des horaires invalide. Utilisez HH:MM.");
            return;
        }
        try {
            LocalTime t1 = LocalTime.parse(nouvelleHeureOuv);
            LocalTime t2 = LocalTime.parse(nouvelleHeureFerm);
            if (!t2.isAfter(t1)) {
                JOptionPane.showMessageDialog(dialog, "L'heure de fermeture doit être après l'heure d'ouverture.");
                return;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(dialog, "Erreur dans le format des heures.");
            return;
        }

        ArrayList<String> nouveauxTypes = new ArrayList<>();
        for (JCheckBox cb : checkBoxes) {
            if (cb.isSelected()) nouveauxTypes.add(cb.getText());
        }

        try {
            File file = new File("utilisateurs.txt");
            BufferedReader readerFile = new BufferedReader(new FileReader(file));
            StringBuilder contenu = new StringBuilder();
            String line;
            while ((line = readerFile.readLine()) != null) {
                if (line.contains(emailActuel)) {
                    String nouvelleLigne = String.join(";", "CENTRE", nouveauNom, nouveauEmail, nouveauMdp, nouvelleAdresse,
                            nouveauTel, nouvelleHeureOuv, nouvelleHeureFerm, nouvelleCapacite);
                    for (String t : nouveauxTypes) {
                        nouvelleLigne += ";" + t;
                    }
                    contenu.append(nouvelleLigne).append("\n");
                } else {
                    contenu.append(line).append("\n");
                }
            }
            readerFile.close();

            BufferedWriter writer = new BufferedWriter(new FileWriter(file));
            writer.write(contenu.toString());
            writer.close();

            // Mise à jour de demandes.txt et depots.txt si email changé
            if (!emailActuel.equals(nouveauEmail)) {
                // MAJ dans demandes.txt
                File fichierDemandes = new File("demandes.txt");
                if (fichierDemandes.exists()) {
                    BufferedReader demandeReader = new BufferedReader(new FileReader(fichierDemandes));
                    StringBuilder demandesContenu = new StringBuilder();
                    while ((line = demandeReader.readLine()) != null) {
                        String[] parts = line.split(";");
                        if (parts.length > 4 && parts[4].equals(emailActuel)) {
                            parts[4] = nouveauEmail;
                            line = String.join(";", parts);
                        }
                        demandesContenu.append(line).append("\n");
                    }
                    demandeReader.close();
                    BufferedWriter demandeWriter = new BufferedWriter(new FileWriter(fichierDemandes));
                    demandeWriter.write(demandesContenu.toString());
                    demandeWriter.close();
                }

                // MAJ dans depots.txt
                File fichierDepots = new File("depots.txt");
                if (fichierDepots.exists()) {
                    BufferedReader depotsReader = new BufferedReader(new FileReader(fichierDepots));
                    StringBuilder depotsContenu = new StringBuilder();
                    while ((line = depotsReader.readLine()) != null) {
                        String[] parts = line.split(";");
                        if (parts.length == 5 && parts[4].equals(emailActuel)) {
                            parts[4] = nouveauEmail;
                            line = String.join(";", parts);
                        }
                        depotsContenu.append(line).append("\n");
                    }
                    depotsReader.close();
                    BufferedWriter depotsWriter = new BufferedWriter(new FileWriter(fichierDepots));
                    depotsWriter.write(depotsContenu.toString());
                    depotsWriter.close();
                }
            }

            FAccueil.mailEntreprise = nouveauEmail;
            JOptionPane.showMessageDialog(dialog, "Données modifiées avec succès.");
            jTextField2.setText("Bienvenue " + nomField.getText());
            dialog.dispose();
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(dialog, "Erreur lors de la sauvegarde.");
        }
    });

    dialog.setVisible(true);    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenuCENTRE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenuCENTRE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenuCENTRE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenuCENTRE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FMenuCENTRE().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Demande;
    private javax.swing.JButton historique_entr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_retour;
    private javax.swing.JLabel jLabel_LOGO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Background;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel jfirst_font;
    // End of variables declaration//GEN-END:variables
}
